export default function Arsenal() { return (<section id="arsenal">
        <div className="chapter-head reveal"><div><p className="chapter-kicker">Chapter 02 · The arsenal</p><h2>Tools for the journey.</h2><p className="chapter-note">Open a category to reveal the foundations and areas I’m building.</p></div><span className="chapter-number" aria-hidden="true">02</span></div>
        <div className="skill-layout">
          <aside className="skill-intro story-panel reveal from-left"><p className="chapter-kicker">A growing toolkit</p><p>Engineering is a collection of connected ideas. I’m learning across circuits, systems, design, and the habits that make good solutions possible.</p><p><strong>Note:</strong> Coding languages are intentionally left out of this version.</p></aside>
          <div className="skill-groups">
            <div className="skill-group reveal"><button className="skill-toggle" aria-expanded="false" type="button"><span><strong>01 / Electronics foundations</strong><small>Principles behind the system</small></span><span className="plus">+</span></button><div className="skill-content"><div className="skill-content-inner"><div className="skill-tags"><span className="skill-tag" style={{'--tag-delay': '0ms'}}>Electrical fundamentals</span><span className="skill-tag" style={{'--tag-delay': '55ms'}}>Electronic fundamentals</span><span className="skill-tag" style={{'--tag-delay': '110ms'}}>Circuit analysis</span><span className="skill-tag" style={{'--tag-delay': '165ms'}}>Digital logic</span></div></div></div></div>
            <div className="skill-group reveal" style={{'--delay': '70ms'}}><button className="skill-toggle" aria-expanded="false" type="button"><span><strong>02 / Embedded systems</strong><small>Where hardware meets software</small></span><span className="plus">+</span></button><div className="skill-content"><div className="skill-content-inner"><div className="skill-tags"><span className="skill-tag">Embedded systems</span><span className="skill-tag" style={{'--tag-delay': '55ms'}}>Microcontrollers</span><span className="skill-tag" style={{'--tag-delay': '110ms'}}>Hardware–software integration</span></div></div></div></div>
            <div className="skill-group reveal" style={{'--delay': '140ms'}}><button className="skill-toggle" aria-expanded="false" type="button"><span><strong>03 / CAD &amp; collaboration</strong><small>Visualizing and sharing ideas</small></span><span className="plus">+</span></button><div className="skill-content"><div className="skill-content-inner"><div className="skill-tags"><span className="skill-tag">Autodesk Fusion</span><span className="skill-tag" style={{'--tag-delay': '55ms'}}>GrabCAD</span><span className="skill-tag" style={{'--tag-delay': '110ms'}}>3D modeling</span><span className="skill-tag" style={{'--tag-delay': '165ms'}}>Team collaboration</span></div></div></div></div>
            <div className="skill-group reveal" style={{'--delay': '210ms'}}><button className="skill-toggle" aria-expanded="false" type="button"><span><strong>04 / Engineering practice</strong><small>How I approach a challenge</small></span><span className="plus">+</span></button><div className="skill-content"><div className="skill-content-inner"><div className="skill-tags"><span className="skill-tag">Git &amp; GitHub</span><span className="skill-tag" style={{'--tag-delay': '55ms'}}>Design thinking</span><span className="skill-tag" style={{'--tag-delay': '110ms'}}>Logical reasoning</span><span className="skill-tag" style={{'--tag-delay': '165ms'}}>Analytical thinking</span><span className="skill-tag" style={{'--tag-delay': '220ms'}}>Technical problem-solving</span></div></div></div></div>
          </div>
        </div>
      </section>); }